"""Interactive mode and novelty classification helpers for project2paper.

This module provides:
1. Interactive mode: phase-by-phase user interaction, checkpoints, config
2. Novelty classification: mark findings as existing work vs novel contributions
3. Multi-format novelty rendering: HTML badges, LaTeX macros, Markdown markers
"""

import json
import os
from typing import Optional

# ─── Novelty Classification ────────────────────────────────────────────

NOVELTY_TYPES = {
    "novel": {
        "label": "Novel Contribution",
        "icon": "🆕",
        "color": "#22c55e",
        "description": "Truly new approach, algorithm, or design introduced by this project",
    },
    "existing": {
        "label": "Existing Work",
        "icon": "📚",
        "color": "#6b7280",
        "description": "Well-known technique, standard practice, or dependency from prior work",
    },
    "improved": {
        "label": "Improved from Prior Work",
        "icon": "✨",
        "color": "#f59e0b",
        "description": "Existing approach that has been significantly adapted, optimized, or extended",
    },
    "baseline": {
        "label": "Baseline / Common Practice",
        "icon": "🔧",
        "color": "#3b82f6",
        "description": "Industry standard, common pattern, or baseline implementation",
    },
}


def render_novelty_marker(novelty_type: str, fmt: str = "markdown") -> str:
    """Render a novelty marker in the specified output format.

    Args:
        novelty_type: One of "novel", "existing", "improved", "baseline"
        fmt: "markdown", "latex", or "html"

    Returns:
        Formatted marker string
    """
    info = NOVELTY_TYPES.get(novelty_type, NOVELTY_TYPES["existing"])
    label = info["label"]
    icon = info["icon"]
    color = info["color"]

    if fmt == "latex":
        r, g, b = _hex_to_rgb(color)
        return (
            f"\\textcolor[RGB]{{{r},{g},{b}}}{{\\textbf{{{icon} {label}}}}}"
        )
    elif fmt == "html":
        return (
            f'<span class="novelty-badge novelty-{novelty_type}" '
            f'style="background:{color}20;color:{color};'
            f'border:1px solid {color};border-radius:4px;'
            f'padding:2px 8px;font-size:0.85em;font-weight:600;">'
            f"{icon} {label}</span>"
        )
    else:
        return f"**{icon} {label}**"


def _hex_to_rgb(hex_color: str) -> tuple:
    hex_color = hex_color.lstrip("#")
    return tuple(int(hex_color[i : i + 2], 16) for i in (0, 2, 4))


# ─── Analysis Outline Template ─────────────────────────────────────────

ANALYSIS_OUTLINE_TEMPLATE = """# Project Analysis Outline

## 1. Existing Work Analysis
{existing_work_summary}

### 1.1 Base Models & Dependencies
{base_models}

### 1.2 Known Patterns & Standard Practices
{known_patterns}

### 1.3 External Dependencies Role
{dependencies_role}

## 2. Novelty Analysis
{novelty_summary}

### 2.1 Novel Contributions (🆕)
{novel_contributions}

### 2.2 Improvements over Prior Work (✨)
{improved_contributions}

### 2.3 Existing Work Referenced (📚)
{existing_contributions}

### 2.4 Baseline / Common Practices (🔧)
{baseline_contributions}

## 3. Paper Structure Proposal
{paper_structure}

### 3.1 Sections
{sections}

### 3.2 Key Claims
{key_claims}

### 3.3 Evidence Sources
{evidence_sources}

---

*Generated by project2paper — review and request modifications below.*
"""


def build_analysis_outline(
    project_name: str,
    existing_work_summary: str,
    base_models: str,
    known_patterns: str,
    dependencies_role: str,
    novelty_summary: str,
    novel_contributions: str,
    improved_contributions: str,
    existing_contributions: str,
    baseline_contributions: str,
    paper_structure: str,
    sections: str,
    key_claims: str,
    evidence_sources: str,
) -> str:
    """Build a formatted analysis outline from structured data."""
    return ANALYSIS_OUTLINE_TEMPLATE.format(
        existing_work_summary=existing_work_summary,
        base_models=base_models,
        known_patterns=known_patterns,
        dependencies_role=dependencies_role,
        novelty_summary=novelty_summary,
        novel_contributions=novel_contributions,
        improved_contributions=improved_contributions,
        existing_contributions=existing_contributions,
        baseline_contributions=baseline_contributions,
        paper_structure=paper_structure,
        sections=sections,
        key_claims=key_claims,
        evidence_sources=evidence_sources,
    )


# ─── Interactive Mode ──────────────────────────────────────────────────

INTERACTIVE_PROMPTS = {
    "phase0_intro": (
        "## Project2Paper Interactive Mode\n\n"
        "I'll guide you through 5 phases to generate a technical paper from your project.\n"
        "You'll have the chance to review and provide feedback at each step.\n\n"
    ),
    "ask_novelty_mode": (
        "**How would you like to identify the novelty points of your project?**\n\n"
        "1. **I'll tell you** — You describe what's novel and what's existing work\n"
        "2. **AI finds them automatically** — I'll analyze the codebase and identify novelty myself\n\n"
        "Which do you prefer? (1 or 2)"
    ),
    "ask_novelty_hints_manual": (
        "**Great, please tell me about your project's novelty:**\n\n"
        "1. What are the **main novel contributions** of this project?\n"
        "2. What parts are **based on existing work** or standard practices?\n"
        "3. Any **related projects or papers** we should reference?\n\n"
        "Please describe in detail."
    ),
    "ask_novelty_hints_auto": (
        "**OK, I'll automatically analyze the codebase to identify novelty.**\n\n"
        "I'll scan for unique algorithms, custom implementations, and deviations from\n"
        "standard practices. You'll have a chance to review and adjust my findings later."
    ),
    "phase1_complete": (
        "### Phase 1 Complete: Project Scan\n\n"
        "Here's a summary of the scanned project:\n\n{summary}\n\n"
        "**Do you want to proceed to Phase 2 (Literature Search & Base Model Discovery)?**\n"
        "If anything looks wrong, I can adjust the scan before continuing."
    ),
    "phase2_complete": (
        "### Phase 2 Complete: Literature Search & Base Model Discovery\n\n"
        "I've analyzed the codebase to find related work, base models, and existing patterns:\n\n"
        "{research_summary}\n\n"
        "**Do you want to proceed to Phase 3 (Novelty Analysis & Outline)?**\n"
        "You can also tell me about any related projects or base models I may have missed."
    ),
    "phase3_complete": (
        "### Phase 3 Complete: Novelty Analysis & Outline\n\n"
        "I've analyzed the project architecture and classified novelty based on Phase 2 findings.\n"
        "The analysis outline has been generated at `{outline_path}`.\n\n"
        "**Do you want to proceed to Phase 4 (Paper Writing)?**\n"
        "Or would you like to modify the analysis outline first?"
    ),
    "outline_review": (
        "### Analysis Outline Review\n\n"
        "Here is the proposed analysis outline for the paper:\n\n"
        "{outline}\n\n"
        "**Do you want to:**\n"
        "1. **Accept and proceed** — Use this outline as-is for the paper\n"
        "2. **Request modifications** — Tell me what to change\n\n"
        "Please choose (1 or 2). If 2, describe what you'd like modified."
    ),
    "outline_loop": (
        "I've updated the outline based on your feedback.\n\n"
        "{outline}\n\n"
        "**Are you satisfied now?** (yes/no)\n"
        "If no, tell me what else to change."
    ),
    "phase4_complete": (
        "### Phase 4 Complete: Paper Draft\n\n"
        "A draft paper has been generated at `{output_path}`.\n"
        "Novelty markers ({marker_type}) are shown inline.\n\n"
        "**Do you want to proceed to Phase 5 (Review & Refine)?**\n"
        "Or would you like me to make adjustments first?"
    ),
    "phase5_complete": (
        "### Phase 5 Complete: Final Paper\n\n"
        "The paper has been reviewed and refined.\n\n"
        "**Final paper: {output_path}**\n\n"
        "Are you satisfied with the result, or would you like further changes?"
    ),
}


def get_interactive_prompt(phase_key: str, **kwargs) -> str:
    """Get an interactive prompt for the specified phase.

    Args:
        phase_key: e.g. "phase0_intro", "phase1_complete"
        **kwargs: Format arguments for the prompt template

    Returns:
        Formatted prompt string
    """
    template = INTERACTIVE_PROMPTS.get(phase_key, "")
    return template.format(**kwargs) if template else ""


# ─── Config Helpers ────────────────────────────────────────────────────

DEFAULT_CONFIG = {
    "interactive": True,
    "novelty_highlight": True,
    "novelty_mode": "auto",
    "novelty_in_title": True,
    "novelty_in_toc": True,
}


def load_config(config_path: str) -> dict:
    """Load config.json and ensure interactive/novelty fields exist."""
    config = {}
    if os.path.exists(config_path):
        with open(config_path, "r") as f:
            config = json.load(f)
    for key, val in DEFAULT_CONFIG.items():
        config.setdefault(key, val)
    return config


def has_novelty_classification(findings_path: str) -> bool:
    """Check if research-findings.json has novelty classifications."""
    if not os.path.exists(findings_path):
        return False
    with open(findings_path, "r") as f:
        findings = json.load(f)
    for entry in findings.get("key_contributions", []):
        if "novelty" in entry:
            return True
    for entry in findings.get("architectural_decisions", []):
        if "novelty" in entry:
            return True
    return False


# ─── Research Summary Generation ───────────────────────────────────────

def generate_research_summary(findings: dict) -> str:
    """Generate a concise summary of research findings for Phase 2 review."""
    lines = []
    base_models = findings.get("base_models", [])
    patterns = findings.get("existing_patterns", [])
    zones = findings.get("potential_novelty_zones", [])

    lines.append(f"**Base models found:** {len(base_models)}")
    for m in base_models:
        lines.append(f"  - {m.get('name', '?')} ({m.get('type', '?')}) — {m.get('modification_level', '?')}")
    lines.append(f"**Known patterns:** {len(patterns)}")
    for p in patterns[:3]:
        lines.append(f"  - {p.get('pattern', '?')}")
    lines.append(f"**Potential novelty zones:** {len(zones)}")
    for z in zones[:3]:
        lines.append(f"  - {z.get('area', '?')}: {z.get('reason', '?')[:80]}")

    return "\n".join(lines)


# ─── Novelty Summary Generation ────────────────────────────────────────

def generate_novelty_summary(findings: dict) -> str:
    """Generate a summary table of novelty classifications."""
    lines = ["| Classification | Count |", "|----------------|-------|"]

    counts = {"novel": 0, "existing": 0, "improved": 0, "baseline": 0}

    for entry in findings.get("key_contributions", []):
        n = entry.get("novelty", "existing")
        if n in counts:
            counts[n] += 1
    for entry in findings.get("architectural_decisions", []):
        n = entry.get("novelty", "existing")
        if n in counts:
            counts[n] += 1

    for nt, count in counts.items():
        marker = render_novelty_marker(nt, fmt="markdown")
        lines.append(f"| {marker} | {count} |")

    return "\n".join(lines)
